### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by skriems** [skriems/welcomescreen-api#4]
- [x] sort todays meetings and show only the latest 4? appointments
- [x] only display meetings table if we have any
- [x] improve/revise the `AuthService` (and Login Component)
- [x] auth guard should redirect to login page
- [x] create/update tests
---
- [x] add credits for the angular-starter project
- [x] create a dist of the UI that is directly shipped and exposed
- [x] use tox
